language: java

sudo: false

jdk:
  - oraclejdk8
  -
before_script:
  - chmod +x gradlew
  -
script:
  - ./gradlew check
  -
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: ebispot:DcHSOumOIyoD1Icc8WVDZe7U